# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge packages over pip as installations are more efficient.
  - python=3.11.5               # https://pyreadiness.org/3.9/
  - pip=23.2.1                  # https://pip.pypa.io/en/stable/news/
  - pip:
      # Define pip packages here -> https://pypi.org/
      - rpaframework==27.0.1    # https://rpaframework.org/releasenotes.html
      - ansible==8.4.0
      - ansible-core==2.15.4
      - ansible-runner==2.3.4
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - colorama==0.4.6
      - cryptography==41.0.3
      - docutils==0.20.1
      - idna==3.4
      - lockfile==0.12.2
      - MarkupSafe==2.1.3
      - packaging==23.1
      - pexpect==4.8.0
      - ptyprocess==0.7.0
      - pycparser==2.21
      - pymongo==4.5.0
      - python-daemon==3.0.1
      - PyYAML==6.0.1
      - requests==2.31.0
      - resolvelib==1.0.1
      - robotframework==6.1.1
      - six==1.16.0
      - urllib3==2.0.4
