- hosts: nfs
  gather_facts: false  
  tasks:
    - name: Fetch config files
      ansible.builtin.include_role:
        name: fetch_files
      vars:
        source: "{{item.path }}/{{item.filename}}"
        destination: "{{default_test_log_path}}{{inventory_hostname}}/{{item.service}}/{{test_date | default(None)}}/{{TEST_ID | default(None)}}/config_files/"
        with_zip: false
      with_items: "{{ conf_files }}"

